[package]
name = "nch_watcher"
version = "0.1.2"
edition = "2021"

[dependencies]
curl = "0.4.46"
regex = "1.10.3"
scraper = "0.19.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3.34", features = ["macros", "parsing", "serde"] }